### ISSUE TITLE
Meadow Guarder gets redirected.

### ISSUE THREAD

**Issue by maitian352** [Suvanth-Erranki/404-Not-Found-Redirect-UserScript#2]
You can try for yourself [here](https://www.youtube.com/watch?v=dQw4w9WgXcQ).

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/152031163-0a425280-f6b7-4262-af73-683bfcee766a.png)

**Comment by Suvanth-Erranki** [comment]
Also, if I hover over the link, I see a youtube video, indicating a rickroll.
